# device-vendor.mk

PRODUCT_COPY_FILES += \
    vendor/samsung/a2corelte/proprietary/build.prop:$(TARGET_COPY_OUT_VENDOR)/build.prop:samsung \
    vendor/samsung/a2corelte/proprietary/compatibility_matrix.xml:$(TARGET_COPY_OUT_VENDOR)/compatibility_matrix.xml:samsung \
    vendor/samsung/a2corelte/proprietary/default.prop:$(TARGET_COPY_OUT_VENDOR)/default.prop:samsung \
    vendor/samsung/a2corelte/proprietary/manifest.xml:$(TARGET_COPY_OUT_VENDOR)/manifest.xml:samsung \
    vendor/samsung/a2corelte/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/00060308060501020000000000000000.tlbin:samsung \
    vendor/samsung/a2corelte/proprietary/app/mcRegistry/020a0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020a0000000000000000000000000000.drbin:samsung \
    vendor/samsung/a2corelte/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000000000.tlbin:samsung \
    vendor/samsung/a2corelte/proprietary/app/mcRegistry/08130000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08130000000000000000000000000000.tlbin:samsung \
    vendor/samsung/a2corelte/proprietary/app/mcRegistry/FFFFFFFFD00000000000000000000016.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/FFFFFFFFD00000000000000000000016.tlbin:samsung \
    vendor/samsung/a2corelte/proprietary/bin/acpi:$(TARGET_COPY_OUT_VENDOR)/bin/acpi:samsung \
    vendor/samsung/a2corelte/proprietary/bin/base64:$(TARGET_COPY_OUT_VENDOR)/bin/base64:samsung \
    vendor/samsung/a2corelte/proprietary/bin/basename:$(TARGET_COPY_OUT_VENDOR)/bin/basename:samsung \
    vendor/samsung/a2corelte/proprietary/bin/blockdev:$(TARGET_COPY_OUT_VENDOR)/bin/blockdev:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cal:$(TARGET_COPY_OUT_VENDOR)/bin/cal:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cat:$(TARGET_COPY_OUT_VENDOR)/bin/cat:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chcon:$(TARGET_COPY_OUT_VENDOR)/bin/chcon:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chgrp:$(TARGET_COPY_OUT_VENDOR)/bin/chgrp:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chmod:$(TARGET_COPY_OUT_VENDOR)/bin/chmod:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chown:$(TARGET_COPY_OUT_VENDOR)/bin/chown:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chroot:$(TARGET_COPY_OUT_VENDOR)/bin/chroot:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chrt:$(TARGET_COPY_OUT_VENDOR)/bin/chrt:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cksum:$(TARGET_COPY_OUT_VENDOR)/bin/cksum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/clear:$(TARGET_COPY_OUT_VENDOR)/bin/clear:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cmp:$(TARGET_COPY_OUT_VENDOR)/bin/cmp:samsung \
    vendor/samsung/a2corelte/proprietary/bin/comm:$(TARGET_COPY_OUT_VENDOR)/bin/comm:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cp:$(TARGET_COPY_OUT_VENDOR)/bin/cp:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cpio:$(TARGET_COPY_OUT_VENDOR)/bin/cpio:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cut:$(TARGET_COPY_OUT_VENDOR)/bin/cut:samsung \
    vendor/samsung/a2corelte/proprietary/bin/date:$(TARGET_COPY_OUT_VENDOR)/bin/date:samsung \
    vendor/samsung/a2corelte/proprietary/bin/df:$(TARGET_COPY_OUT_VENDOR)/bin/df:samsung \
    vendor/samsung/a2corelte/proprietary/bin/diff:$(TARGET_COPY_OUT_VENDOR)/bin/diff:samsung \
    vendor/samsung/a2corelte/proprietary/bin/dirname:$(TARGET_COPY_OUT_VENDOR)/bin/dirname:samsung \
    vendor/samsung/a2corelte/proprietary/bin/dmesg:$(TARGET_COPY_OUT_VENDOR)/bin/dmesg:samsung \
    vendor/samsung/a2corelte/proprietary/bin/dos2unix:$(TARGET_COPY_OUT_VENDOR)/bin/dos2unix:samsung \
    vendor/samsung/a2corelte/proprietary/bin/du:$(TARGET_COPY_OUT_VENDOR)/bin/du:samsung \
    vendor/samsung/a2corelte/proprietary/bin/echo:$(TARGET_COPY_OUT_VENDOR)/bin/echo:samsung \
    vendor/samsung/a2corelte/proprietary/bin/egrep:$(TARGET_COPY_OUT_VENDOR)/bin/egrep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/env:$(TARGET_COPY_OUT_VENDOR)/bin/env:samsung \
    vendor/samsung/a2corelte/proprietary/bin/expand:$(TARGET_COPY_OUT_VENDOR)/bin/expand:samsung \
    vendor/samsung/a2corelte/proprietary/bin/expr:$(TARGET_COPY_OUT_VENDOR)/bin/expr:samsung \
    vendor/samsung/a2corelte/proprietary/bin/fallocate:$(TARGET_COPY_OUT_VENDOR)/bin/fallocate:samsung \
    vendor/samsung/a2corelte/proprietary/bin/false:$(TARGET_COPY_OUT_VENDOR)/bin/false:samsung \
    vendor/samsung/a2corelte/proprietary/bin/fgrep:$(TARGET_COPY_OUT_VENDOR)/bin/fgrep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/file:$(TARGET_COPY_OUT_VENDOR)/bin/file:samsung \
    vendor/samsung/a2corelte/proprietary/bin/find:$(TARGET_COPY_OUT_VENDOR)/bin/find:samsung \
    vendor/samsung/a2corelte/proprietary/bin/flock:$(TARGET_COPY_OUT_VENDOR)/bin/flock:samsung \
    vendor/samsung/a2corelte/proprietary/bin/free:$(TARGET_COPY_OUT_VENDOR)/bin/free:samsung \
    vendor/samsung/a2corelte/proprietary/bin/getenforce:$(TARGET_COPY_OUT_VENDOR)/bin/getenforce:samsung \
    vendor/samsung/a2corelte/proprietary/bin/getprop:$(TARGET_COPY_OUT_VENDOR)/bin/getprop:samsung \
    vendor/samsung/a2corelte/proprietary/bin/grep:$(TARGET_COPY_OUT_VENDOR)/bin/grep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/groups:$(TARGET_COPY_OUT_VENDOR)/bin/groups:samsung \
    vendor/samsung/a2corelte/proprietary/bin/gunzip:$(TARGET_COPY_OUT_VENDOR)/bin/gunzip:samsung \
    vendor/samsung/a2corelte/proprietary/bin/gzip:$(TARGET_COPY_OUT_VENDOR)/bin/gzip:samsung \
    vendor/samsung/a2corelte/proprietary/bin/head:$(TARGET_COPY_OUT_VENDOR)/bin/head:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hostapd:$(TARGET_COPY_OUT_VENDOR)/bin/hostapd:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hostname:$(TARGET_COPY_OUT_VENDOR)/bin/hostname:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hwclock:$(TARGET_COPY_OUT_VENDOR)/bin/hwclock:samsung \
    vendor/samsung/a2corelte/proprietary/bin/id:$(TARGET_COPY_OUT_VENDOR)/bin/id:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ifconfig:$(TARGET_COPY_OUT_VENDOR)/bin/ifconfig:samsung \
    vendor/samsung/a2corelte/proprietary/bin/inotifyd:$(TARGET_COPY_OUT_VENDOR)/bin/inotifyd:samsung \
    vendor/samsung/a2corelte/proprietary/bin/insmod:$(TARGET_COPY_OUT_VENDOR)/bin/insmod:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ionice:$(TARGET_COPY_OUT_VENDOR)/bin/ionice:samsung \
    vendor/samsung/a2corelte/proprietary/bin/iorenice:$(TARGET_COPY_OUT_VENDOR)/bin/iorenice:samsung \
    vendor/samsung/a2corelte/proprietary/bin/kill:$(TARGET_COPY_OUT_VENDOR)/bin/kill:samsung \
    vendor/samsung/a2corelte/proprietary/bin/killall:$(TARGET_COPY_OUT_VENDOR)/bin/killall:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ln:$(TARGET_COPY_OUT_VENDOR)/bin/ln:samsung \
    vendor/samsung/a2corelte/proprietary/bin/load_policy:$(TARGET_COPY_OUT_VENDOR)/bin/load_policy:samsung \
    vendor/samsung/a2corelte/proprietary/bin/log:$(TARGET_COPY_OUT_VENDOR)/bin/log:samsung \
    vendor/samsung/a2corelte/proprietary/bin/logname:$(TARGET_COPY_OUT_VENDOR)/bin/logname:samsung \
    vendor/samsung/a2corelte/proprietary/bin/losetup:$(TARGET_COPY_OUT_VENDOR)/bin/losetup:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ls:$(TARGET_COPY_OUT_VENDOR)/bin/ls:samsung \
    vendor/samsung/a2corelte/proprietary/bin/lsmod:$(TARGET_COPY_OUT_VENDOR)/bin/lsmod:samsung \
    vendor/samsung/a2corelte/proprietary/bin/lsof:$(TARGET_COPY_OUT_VENDOR)/bin/lsof:samsung \
    vendor/samsung/a2corelte/proprietary/bin/lspci:$(TARGET_COPY_OUT_VENDOR)/bin/lspci:samsung \
    vendor/samsung/a2corelte/proprietary/bin/lsusb:$(TARGET_COPY_OUT_VENDOR)/bin/lsusb:samsung \
    vendor/samsung/a2corelte/proprietary/bin/md5sum:$(TARGET_COPY_OUT_VENDOR)/bin/md5sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/microcom:$(TARGET_COPY_OUT_VENDOR)/bin/microcom:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mkdir:$(TARGET_COPY_OUT_VENDOR)/bin/mkdir:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mkfifo:$(TARGET_COPY_OUT_VENDOR)/bin/mkfifo:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mknod:$(TARGET_COPY_OUT_VENDOR)/bin/mknod:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mkswap:$(TARGET_COPY_OUT_VENDOR)/bin/mkswap:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mktemp:$(TARGET_COPY_OUT_VENDOR)/bin/mktemp:samsung \
    vendor/samsung/a2corelte/proprietary/bin/modinfo:$(TARGET_COPY_OUT_VENDOR)/bin/modinfo:samsung \
    vendor/samsung/a2corelte/proprietary/bin/modprobe:$(TARGET_COPY_OUT_VENDOR)/bin/modprobe:samsung \
    vendor/samsung/a2corelte/proprietary/bin/more:$(TARGET_COPY_OUT_VENDOR)/bin/more:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mount:$(TARGET_COPY_OUT_VENDOR)/bin/mount:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mountpoint:$(TARGET_COPY_OUT_VENDOR)/bin/mountpoint:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mv:$(TARGET_COPY_OUT_VENDOR)/bin/mv:samsung \
    vendor/samsung/a2corelte/proprietary/bin/netstat:$(TARGET_COPY_OUT_VENDOR)/bin/netstat:samsung \
    vendor/samsung/a2corelte/proprietary/bin/nice:$(TARGET_COPY_OUT_VENDOR)/bin/nice:samsung \
    vendor/samsung/a2corelte/proprietary/bin/nl:$(TARGET_COPY_OUT_VENDOR)/bin/nl:samsung \
    vendor/samsung/a2corelte/proprietary/bin/nohup:$(TARGET_COPY_OUT_VENDOR)/bin/nohup:samsung \
    vendor/samsung/a2corelte/proprietary/bin/od:$(TARGET_COPY_OUT_VENDOR)/bin/od:samsung \
    vendor/samsung/a2corelte/proprietary/bin/paste:$(TARGET_COPY_OUT_VENDOR)/bin/paste:samsung \
    vendor/samsung/a2corelte/proprietary/bin/patch:$(TARGET_COPY_OUT_VENDOR)/bin/patch:samsung \
    vendor/samsung/a2corelte/proprietary/bin/pgrep:$(TARGET_COPY_OUT_VENDOR)/bin/pgrep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/pidof:$(TARGET_COPY_OUT_VENDOR)/bin/pidof:samsung \
    vendor/samsung/a2corelte/proprietary/bin/pkill:$(TARGET_COPY_OUT_VENDOR)/bin/pkill:samsung \
    vendor/samsung/a2corelte/proprietary/bin/pmap:$(TARGET_COPY_OUT_VENDOR)/bin/pmap:samsung \
    vendor/samsung/a2corelte/proprietary/bin/printenv:$(TARGET_COPY_OUT_VENDOR)/bin/printenv:samsung \
    vendor/samsung/a2corelte/proprietary/bin/printf:$(TARGET_COPY_OUT_VENDOR)/bin/printf:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ps:$(TARGET_COPY_OUT_VENDOR)/bin/ps:samsung \
    vendor/samsung/a2corelte/proprietary/bin/pwd:$(TARGET_COPY_OUT_VENDOR)/bin/pwd:samsung \
    vendor/samsung/a2corelte/proprietary/bin/readlink:$(TARGET_COPY_OUT_VENDOR)/bin/readlink:samsung \
    vendor/samsung/a2corelte/proprietary/bin/realpath:$(TARGET_COPY_OUT_VENDOR)/bin/realpath:samsung \
    vendor/samsung/a2corelte/proprietary/bin/renice:$(TARGET_COPY_OUT_VENDOR)/bin/renice:samsung \
    vendor/samsung/a2corelte/proprietary/bin/restorecon:$(TARGET_COPY_OUT_VENDOR)/bin/restorecon:samsung \
    vendor/samsung/a2corelte/proprietary/bin/rm:$(TARGET_COPY_OUT_VENDOR)/bin/rm:samsung \
    vendor/samsung/a2corelte/proprietary/bin/rmdir:$(TARGET_COPY_OUT_VENDOR)/bin/rmdir:samsung \
    vendor/samsung/a2corelte/proprietary/bin/rmmod:$(TARGET_COPY_OUT_VENDOR)/bin/rmmod:samsung \
    vendor/samsung/a2corelte/proprietary/bin/runcon:$(TARGET_COPY_OUT_VENDOR)/bin/runcon:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sed:$(TARGET_COPY_OUT_VENDOR)/bin/sed:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sendevent:$(TARGET_COPY_OUT_VENDOR)/bin/sendevent:samsung \
    vendor/samsung/a2corelte/proprietary/bin/seq:$(TARGET_COPY_OUT_VENDOR)/bin/seq:samsung \
    vendor/samsung/a2corelte/proprietary/bin/setenforce:$(TARGET_COPY_OUT_VENDOR)/bin/setenforce:samsung \
    vendor/samsung/a2corelte/proprietary/bin/setprop:$(TARGET_COPY_OUT_VENDOR)/bin/setprop:samsung \
    vendor/samsung/a2corelte/proprietary/bin/setsid:$(TARGET_COPY_OUT_VENDOR)/bin/setsid:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sh:$(TARGET_COPY_OUT_VENDOR)/bin/sh:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sha1sum:$(TARGET_COPY_OUT_VENDOR)/bin/sha1sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sha224sum:$(TARGET_COPY_OUT_VENDOR)/bin/sha224sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sha256sum:$(TARGET_COPY_OUT_VENDOR)/bin/sha256sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sha384sum:$(TARGET_COPY_OUT_VENDOR)/bin/sha384sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sha512sum:$(TARGET_COPY_OUT_VENDOR)/bin/sha512sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sleep:$(TARGET_COPY_OUT_VENDOR)/bin/sleep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sort:$(TARGET_COPY_OUT_VENDOR)/bin/sort:samsung \
    vendor/samsung/a2corelte/proprietary/bin/split:$(TARGET_COPY_OUT_VENDOR)/bin/split:samsung \
    vendor/samsung/a2corelte/proprietary/bin/start:$(TARGET_COPY_OUT_VENDOR)/bin/start:samsung \
    vendor/samsung/a2corelte/proprietary/bin/stat:$(TARGET_COPY_OUT_VENDOR)/bin/stat:samsung \
    vendor/samsung/a2corelte/proprietary/bin/stop:$(TARGET_COPY_OUT_VENDOR)/bin/stop:samsung \
    vendor/samsung/a2corelte/proprietary/bin/strings:$(TARGET_COPY_OUT_VENDOR)/bin/strings:samsung \
    vendor/samsung/a2corelte/proprietary/bin/swapoff:$(TARGET_COPY_OUT_VENDOR)/bin/swapoff:samsung \
    vendor/samsung/a2corelte/proprietary/bin/swapon:$(TARGET_COPY_OUT_VENDOR)/bin/swapon:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sync:$(TARGET_COPY_OUT_VENDOR)/bin/sync:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sysctl:$(TARGET_COPY_OUT_VENDOR)/bin/sysctl:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tac:$(TARGET_COPY_OUT_VENDOR)/bin/tac:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tail:$(TARGET_COPY_OUT_VENDOR)/bin/tail:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tar:$(TARGET_COPY_OUT_VENDOR)/bin/tar:samsung \
    vendor/samsung/a2corelte/proprietary/bin/taskset:$(TARGET_COPY_OUT_VENDOR)/bin/taskset:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tee:$(TARGET_COPY_OUT_VENDOR)/bin/tee:samsung \
    vendor/samsung/a2corelte/proprietary/bin/time:$(TARGET_COPY_OUT_VENDOR)/bin/time:samsung \
    vendor/samsung/a2corelte/proprietary/bin/timeout:$(TARGET_COPY_OUT_VENDOR)/bin/timeout:samsung \
    vendor/samsung/a2corelte/proprietary/bin/top:$(TARGET_COPY_OUT_VENDOR)/bin/top:samsung \
    vendor/samsung/a2corelte/proprietary/bin/touch:$(TARGET_COPY_OUT_VENDOR)/bin/touch:samsung \
    vendor/samsung/a2corelte/proprietary/bin/toybox_vendor:$(TARGET_COPY_OUT_VENDOR)/bin/toybox_vendor:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tr:$(TARGET_COPY_OUT_VENDOR)/bin/tr:samsung \
    vendor/samsung/a2corelte/proprietary/bin/true:$(TARGET_COPY_OUT_VENDOR)/bin/true:samsung \
    vendor/samsung/a2corelte/proprietary/bin/truncate:$(TARGET_COPY_OUT_VENDOR)/bin/truncate:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tty:$(TARGET_COPY_OUT_VENDOR)/bin/tty:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tzdaemon:$(TARGET_COPY_OUT_VENDOR)/bin/tzdaemon:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ulimit:$(TARGET_COPY_OUT_VENDOR)/bin/ulimit:samsung \
    vendor/samsung/a2corelte/proprietary/bin/umount:$(TARGET_COPY_OUT_VENDOR)/bin/umount:samsung \
    vendor/samsung/a2corelte/proprietary/bin/uname:$(TARGET_COPY_OUT_VENDOR)/bin/uname:samsung \
    vendor/samsung/a2corelte/proprietary/bin/uniq:$(TARGET_COPY_OUT_VENDOR)/bin/uniq:samsung \
    vendor/samsung/a2corelte/proprietary/bin/unix2dos:$(TARGET_COPY_OUT_VENDOR)/bin/unix2dos:samsung \
    vendor/samsung/a2corelte/proprietary/bin/uptime:$(TARGET_COPY_OUT_VENDOR)/bin/uptime:samsung \
    vendor/samsung/a2corelte/proprietary/bin/usleep:$(TARGET_COPY_OUT_VENDOR)/bin/usleep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/uudecode:$(TARGET_COPY_OUT_VENDOR)/bin/uudecode:samsung \
    vendor/samsung/a2corelte/proprietary/bin/uuencode:$(TARGET_COPY_OUT_VENDOR)/bin/uuencode:samsung \
    vendor/samsung/a2corelte/proprietary/bin/vmstat:$(TARGET_COPY_OUT_VENDOR)/bin/vmstat:samsung \
    vendor/samsung/a2corelte/proprietary/bin/vndservice:$(TARGET_COPY_OUT_VENDOR)/bin/vndservice:samsung \
    vendor/samsung/a2corelte/proprietary/bin/vndservicemanager:$(TARGET_COPY_OUT_VENDOR)/bin/vndservicemanager:samsung \
    vendor/samsung/a2corelte/proprietary/bin/wc:$(TARGET_COPY_OUT_VENDOR)/bin/wc:samsung \
    vendor/samsung/a2corelte/proprietary/bin/which:$(TARGET_COPY_OUT_VENDOR)/bin/which:samsung \
    vendor/samsung/a2corelte/proprietary/bin/whoami:$(TARGET_COPY_OUT_VENDOR)/bin/whoami:samsung \
    vendor/samsung/a2corelte/proprietary/bin/xargs:$(TARGET_COPY_OUT_VENDOR)/bin/xargs:samsung \
    vendor/samsung/a2corelte/proprietary/bin/xxd:$(TARGET_COPY_OUT_VENDOR)/bin/xxd:samsung \
    vendor/samsung/a2corelte/proprietary/bin/yes:$(TARGET_COPY_OUT_VENDOR)/bin/yes:samsung \
    vendor/samsung/a2corelte/proprietary/bin/zcat:$(TARGET_COPY_OUT_VENDOR)/bin/zcat:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.audio@2.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.audio@2.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.bluetooth@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.bluetooth@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.camera.provider@2.4-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.camera.provider@2.4-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.configstore@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.configstore@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.drm@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.drm@1.0-service.widevine:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm@1.0-service.widevine:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.gatekeeper@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.graphics.allocator@2.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.graphics.allocator@2.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.graphics.composer@2.1-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.graphics.composer@2.1-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.health@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.health@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.keymaster@3.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.keymaster@3.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.light@2.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.light@2.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.media.omx@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.media.omx@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.memtrack@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.memtrack@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.power@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.power@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.sensors@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.sensors@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.thermal@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.thermal@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.vibrator@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.vibrator@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.wifi@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.wifi@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/gpsd:$(TARGET_COPY_OUT_VENDOR)/bin/hw/gpsd:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/macloader:$(TARGET_COPY_OUT_VENDOR)/bin/hw/macloader:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/mfgloader:$(TARGET_COPY_OUT_VENDOR)/bin/hw/mfgloader:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/rild:$(TARGET_COPY_OUT_VENDOR)/bin/hw/rild:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/vendor.samsung.hardware.gnss@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.samsung.hardware.gnss@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/vendor.samsung.hardware.miscpower@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.samsung.hardware.miscpower@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/wpa_supplicant:$(TARGET_COPY_OUT_VENDOR)/bin/hw/wpa_supplicant:samsung \
    vendor/samsung/a2corelte/proprietary/etc/NOTICE.xml.gz:$(TARGET_COPY_OUT_VENDOR)/etc/NOTICE.xml.gz:samsung \
    vendor/samsung/a2corelte/proprietary/etc/SoundBoosterParam.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SoundBoosterParam.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/a2dp_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/a2dp_audio_policy_configuration.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/audio_effects_common.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_common.conf:samsung \
    vendor/samsung/a2corelte/proprietary/etc/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/audio_policy_configuration_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_sec.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/fs_config_dirs:$(TARGET_COPY_OUT_VENDOR)/etc/fs_config_dirs:samsung \
    vendor/samsung/a2corelte/proprietary/etc/fs_config_files:$(TARGET_COPY_OUT_VENDOR)/etc/fs_config_files:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs_google_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_audio.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs_google_telephony.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_telephony.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs_google_video.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_video.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs_google_video_le.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_video_le.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/mixer_gains.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_gains.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/mkshrc:$(TARGET_COPY_OUT_VENDOR)/etc/mkshrc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/plmn_delta_usacdma.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usacdma.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/plmn_se13.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/r_submix_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/r_submix_audio_policy_configuration.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/usb_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usb_audio_policy_configuration.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/ACG/permissions/android.hardware.telephony.cdma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/carrier/ACG/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/BST/permissions/android.hardware.telephony.cdma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/carrier/BST/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/CCT/permissions/android.hardware.telephony.cdma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/carrier/CCT/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/LRA/permissions/android.hardware.telephony.cdma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/carrier/LRA/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/SPR/permissions/android.hardware.telephony.cdma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/carrier/SPR/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/TFN/permissions/android.hardware.telephony.cdma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/carrier/TFN/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/USC/permissions/android.hardware.telephony.cdma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/carrier/USC/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/VMU/permissions/android.hardware.telephony.cdma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/carrier/VMU/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/VZW/permissions/android.hardware.telephony.cdma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/carrier/VZW/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/XAS/permissions/android.hardware.telephony.cdma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/carrier/XAS/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem:samsung \
    vendor/samsung/a2corelte/proprietary/etc/gnss/gps.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cfg:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.audio@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.audio@2.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.bluetooth@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.camera.provider@2.4-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider@2.4-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.configstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.configstore@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.drm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.drm@1.0-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.0-service.widevine.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.gatekeeper@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.graphics.allocator@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@2.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.graphics.composer@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@2.1-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.health@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.health@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.keymaster@3.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.light@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.light@2.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.media.omx@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.omx@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.memtrack@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.memtrack@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.power@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.power@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.sensors@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.thermal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.vibrator@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.vibrator@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.wifi@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/hostapd.android.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hostapd.android.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/init.vendor.rilchip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilchip.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rild.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/vendor.samsung.hardware.gnss@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/vendor.samsung.hardware.miscpower@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.miscpower@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/vndservicemanager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vndservicemanager.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/AzControlParams_SPEAKER.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/AzControlParams_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/LVAZFS_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/LVAZFS_Configuration.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/LVVEFS_Rx_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/LVVEFS_Rx_Configuration.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/LVVEFS_Tx_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/LVVEFS_Tx_Configuration.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_EARPIECE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_SPEAKER.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_EARPIECE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_SPEAKER.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_EARPIECE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_SPEAKER.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_EARPIECE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_SPEAKER.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_EARPIECE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_SPEAKER.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_EARPIECE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_SPEAKER.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_EARPIECE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_SPEAKER.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.camera.flash-autofocus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.flash-autofocus.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.camera.front.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.front.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.location.gps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.location.gps.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.opengles.aep.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.opengles.aep.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.sensor.accelerometer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.accelerometer.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.sensor.proximity.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.proximity.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.telephony.gsm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.telephony.gsm.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.usb.accessory.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.accessory.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.usb.host.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.host.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.vulkan.level.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.level.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.vulkan.version.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.version.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.wifi.direct.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.direct.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.wifi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/handheld_core_hardware.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/handheld_core_hardware.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_apsta.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_apsta.bin_36:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_apsta.bin_36:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_clm.blob:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_clm.blob:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_mfg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_mfg.bin_36:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin_36:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_sta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_sta.bin_36:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin_36:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/cred.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/cred.conf:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/indoorchannel.info:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/indoorchannel.info:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/nvram.txt_36:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram.txt_36:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/bcm43436B0_V0086.0141.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm43436B0_V0086.0141.hcd:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/bcm43436B0_V0096.0154.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm43436B0_V0096.0154.hcd:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/fimc_is_lib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_lib.bin:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/setfile_5e9.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_5e9.bin:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/setfile_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_gc5035.bin:samsung \
    vendor/samsung/a2corelte/proprietary/lib/android.hidl.base@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hidl.base@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/camera.device@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera.device@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/camera.device@3.2-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera.device@3.2-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/camera.device@3.3-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera.device@3.3-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libExynosHWCService.so:$(TARGET_COPY_OUT_VENDOR)/lib/libExynosHWCService.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libExynosOMX_Core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libExynosOMX_Core.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libExynosOMX_Resourcemanager.so:$(TARGET_COPY_OUT_VENDOR)/lib/libExynosOMX_Resourcemanager.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libLifevibes_lvverx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLifevibes_lvverx.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libLifevibes_lvvetx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLifevibes_lvvetx.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libMcClient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMcClient.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libOpenCL.so.1:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so.1:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libOpenCL.so.1.1:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so.1.1:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libSamsungPostProcessConvertor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSamsungPostProcessConvertor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/lib_SamsungRec_06006.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SamsungRec_06006.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/lib_SoundAlive_SRC384_ver300.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SoundAlive_SRC384_ver300.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/lib_soundaliveresampler.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_soundaliveresampler.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libalsautils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libalsautils.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libandroid_ssrm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libandroid_ssrm.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libarcsoft_beautyshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_beautyshot.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libarcsoft_beautyshot_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_beautyshot_preview.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libaudio-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudio-ril.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libaudioroute.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioroute.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libavservices_minijail_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libavservices_minijail_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libbt-vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbt-vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libcordon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcordon.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libcsc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcsc.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libeffects.so:$(TARGET_COPY_OUT_VENDOR)/lib/libeffects.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynoscamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynoscamera.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynoscamera3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynoscamera3.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynosdisplay.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynosdisplay.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynosgscaler.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynosgscaler.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynosscaler.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynosscaler.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynosutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynosutils.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynosv4l2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynosv4l2.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libfloatingfeature.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfloatingfeature.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libhdmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhdmi.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libhwc2on1adapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwc2on1adapter.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libhwcutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwcutils.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libhwjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwjpeg.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libhwminijail.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwminijail.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libion_exynos.so:$(TARGET_COPY_OUT_VENDOR)/lib/libion_exynos.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libkeymaster2_mdfpp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeymaster2_mdfpp.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libkeymaster_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeymaster_helper.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libkeystore-engine-wifi-hidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeystore-engine-wifi-hidl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libkeystore-wifi-hidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeystore-wifi-hidl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libmediacodecservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmediacodecservice.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libminijail_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libminijail_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libmpbase.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmpbase.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libmpbase_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmpbase_preview.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libmpp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmpp.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libnbaio_mono.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnbaio_mono.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libpreprocessing_nxp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpreprocessing_nxp.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/librecordalive.so:$(TARGET_COPY_OUT_VENDOR)/lib/librecordalive.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libreference-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libreference-ril.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/librilutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/librilutils.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsamsungDiamondVoice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungDiamondVoice.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsec-ril-dsds.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril-dsds.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsec-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsecaudioinfo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecaudioinfo.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsecnativefeature.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecnativefeature.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libselinux_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libselinux_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsensorlistener.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensorlistener.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsensorndkbridge.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensorndkbridge.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libstagefrighthw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefrighthw.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libstainkiller.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstainkiller.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libteecl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libteecl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libtinyalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtinyalsa.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libtinycompress.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtinycompress.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libuniapi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libuniapi.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libuniplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libuniplugin.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libuuid.so:$(TARGET_COPY_OUT_VENDOR)/lib/libuuid.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libvideobeautycapture_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvideobeautycapture_interface.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libvideobeautypreview_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvideobeautypreview_interface.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libvirtualdisplay.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvirtualdisplay.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libvndsecril-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvndsecril-client.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libwebrtc_audio_preprocessing.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwebrtc_audio_preprocessing.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libwifi-hal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwifi-hal.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libwpa_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwpa_client.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libwrappergps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwrappergps.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libwvhidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvhidl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.gnss@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.samsung.hardware.gnss@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.miscpower@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.samsung.hardware.miscpower@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.radio.channel@1.0_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.samsung.hardware.radio.channel@1.0_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.radio.secoemhook@1.0_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.samsung.hardware.radio.secoemhook@1.0_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.radio@1.1_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.samsung.hardware.radio@1.1_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.wifi.sec_hostapd@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.samsung.hardware.wifi.sec_hostapd@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.wifi.supplicant@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.samsung.hardware.wifi.supplicant@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.security.skeymaster@3.0_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.samsung.security.skeymaster@3.0_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.audio.effect@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.audio.effect@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.audio@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.audio@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.bluetooth@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.bluetooth@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.camera.provider@2.4-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.camera.provider@2.4-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.drm@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.drm@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.gatekeeper@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.gatekeeper@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.gnss@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.gnss@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.graphics.allocator@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.graphics.allocator@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.graphics.composer@2.1-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.graphics.composer@2.1-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.graphics.mapper@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.graphics.mapper@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.health@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.health@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.keymaster@3.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.keymaster@3.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.light@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.light@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.memtrack@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.memtrack@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.power@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.power@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.sensors@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.sensors@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.soundtrigger@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.soundtrigger@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.thermal@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.thermal@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.vibrator@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.vibrator@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/audio.primary.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/audio.primary.universal7870_go.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.universal7870_go.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/audio.r_submix.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.r_submix.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/audio.usb.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.usb.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/camera.universal7870_go.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.universal7870_go.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/gatekeeper.exynos7870.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.exynos7870.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/gps.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/gralloc.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/gralloc.exynos5.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.exynos5.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/hwcomposer.exynos5.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.exynos5.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/keystore.mdfpp.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.mdfpp.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/lights.exynos5.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/lights.exynos5.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/local_time.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/local_time.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/memtrack.exynos5.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.exynos5.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/power.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/power.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/power.universal7870_go.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/power.universal7870_go.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/sensors.universal7870_go.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.universal7870_go.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/vendor.samsung.hardware.gnss@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vendor.samsung.hardware.gnss@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/vendor.samsung.security.skeymaster@3.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vendor.samsung.security.skeymaster@3.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/vibrator.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vibrator.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/vulkan.exynos5.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vulkan.exynos5.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/mediacas/libclearkeycasplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediacas/libclearkeycasplugin.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libdrmclearkeyplugin.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.AVC.Decoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.AVC.Encoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.HEVC.Decoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.HEVC.Encoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.VP8.Decoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.VP8.Encoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.WMV.Decoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libLifevibes_lvverx.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libLifevibes_lvverx.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libLifevibes_lvvetx.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libLifevibes_lvvetx.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libbundlewrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libbundlewrapper.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libdownmix.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libdownmix.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libeffectproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libeffectproxy.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libldnhncr.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libldnhncr.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libreverbwrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libreverbwrapper.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libvisualizer.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libvisualizer.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vndk-sp/libion.so:$(TARGET_COPY_OUT_VENDOR)/lib/vndk-sp/libion.so:samsung \
    vendor/samsung/a2corelte/proprietary/media/LMspeed_508.emd:$(TARGET_COPY_OUT_VENDOR)/media/LMspeed_508.emd:samsung \
    vendor/samsung/a2corelte/proprietary/media/PFFprec_600.emd:$(TARGET_COPY_OUT_VENDOR)/media/PFFprec_600.emd:samsung \
    vendor/samsung/a2corelte/proprietary/tee/00000000-0000-0000-0000-474154454b45:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-474154454b45:samsung \
    vendor/samsung/a2corelte/proprietary/tee/00000000-0000-0000-0000-4b45594d5354:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-4b45594d5354:samsung \
    vendor/samsung/a2corelte/proprietary/tee/00000000-0000-0000-0000-505256544545:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-505256544545:samsung \
    vendor/samsung/a2corelte/proprietary/tee/startup.tzar:$(TARGET_COPY_OUT_VENDOR)/tee/startup.tzar:samsung \
    vendor/samsung/a2corelte/proprietary/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_:$(TARGET_COPY_OUT_VENDOR)/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_:samsung
