# device-vendor.mk

PRODUCT_COPY_FILES += \
    vendor/samsung/a2corelte/proprietary/build.prop:system/vendor/build.prop:samsung \
    vendor/samsung/a2corelte/proprietary/compatibility_matrix.xml:system/vendor/compatibility_matrix.xml:samsung \
    vendor/samsung/a2corelte/proprietary/default.prop:system/vendor/default.prop:samsung \
    vendor/samsung/a2corelte/proprietary/manifest.xml:system/vendor/manifest.xml:samsung \
    vendor/samsung/a2corelte/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/vendor/app/mcRegistry/00060308060501020000000000000000.tlbin:samsung \
    vendor/samsung/a2corelte/proprietary/app/mcRegistry/020a0000000000000000000000000000.drbin:system/vendor/app/mcRegistry/020a0000000000000000000000000000.drbin:samsung \
    vendor/samsung/a2corelte/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/07060000000000000000000000000000.tlbin:samsung \
    vendor/samsung/a2corelte/proprietary/app/mcRegistry/08130000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin:samsung \
    vendor/samsung/a2corelte/proprietary/app/mcRegistry/FFFFFFFFD00000000000000000000016.tlbin:system/vendor/app/mcRegistry/FFFFFFFFD00000000000000000000016.tlbin:samsung \
    vendor/samsung/a2corelte/proprietary/bin/acpi:system/vendor/bin/acpi:samsung \
    vendor/samsung/a2corelte/proprietary/bin/base64:system/vendor/bin/base64:samsung \
    vendor/samsung/a2corelte/proprietary/bin/basename:system/vendor/bin/basename:samsung \
    vendor/samsung/a2corelte/proprietary/bin/blockdev:system/vendor/bin/blockdev:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cal:system/vendor/bin/cal:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cat:system/vendor/bin/cat:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chcon:system/vendor/bin/chcon:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chgrp:system/vendor/bin/chgrp:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chmod:system/vendor/bin/chmod:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chown:system/vendor/bin/chown:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chroot:system/vendor/bin/chroot:samsung \
    vendor/samsung/a2corelte/proprietary/bin/chrt:system/vendor/bin/chrt:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cksum:system/vendor/bin/cksum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/clear:system/vendor/bin/clear:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cmp:system/vendor/bin/cmp:samsung \
    vendor/samsung/a2corelte/proprietary/bin/comm:system/vendor/bin/comm:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cp:system/vendor/bin/cp:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cpio:system/vendor/bin/cpio:samsung \
    vendor/samsung/a2corelte/proprietary/bin/cut:system/vendor/bin/cut:samsung \
    vendor/samsung/a2corelte/proprietary/bin/date:system/vendor/bin/date:samsung \
    vendor/samsung/a2corelte/proprietary/bin/df:system/vendor/bin/df:samsung \
    vendor/samsung/a2corelte/proprietary/bin/diff:system/vendor/bin/diff:samsung \
    vendor/samsung/a2corelte/proprietary/bin/dirname:system/vendor/bin/dirname:samsung \
    vendor/samsung/a2corelte/proprietary/bin/dmesg:system/vendor/bin/dmesg:samsung \
    vendor/samsung/a2corelte/proprietary/bin/dos2unix:system/vendor/bin/dos2unix:samsung \
    vendor/samsung/a2corelte/proprietary/bin/du:system/vendor/bin/du:samsung \
    vendor/samsung/a2corelte/proprietary/bin/echo:system/vendor/bin/echo:samsung \
    vendor/samsung/a2corelte/proprietary/bin/egrep:system/vendor/bin/egrep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/env:system/vendor/bin/env:samsung \
    vendor/samsung/a2corelte/proprietary/bin/expand:system/vendor/bin/expand:samsung \
    vendor/samsung/a2corelte/proprietary/bin/expr:system/vendor/bin/expr:samsung \
    vendor/samsung/a2corelte/proprietary/bin/fallocate:system/vendor/bin/fallocate:samsung \
    vendor/samsung/a2corelte/proprietary/bin/false:system/vendor/bin/false:samsung \
    vendor/samsung/a2corelte/proprietary/bin/fgrep:system/vendor/bin/fgrep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/file:system/vendor/bin/file:samsung \
    vendor/samsung/a2corelte/proprietary/bin/find:system/vendor/bin/find:samsung \
    vendor/samsung/a2corelte/proprietary/bin/flock:system/vendor/bin/flock:samsung \
    vendor/samsung/a2corelte/proprietary/bin/free:system/vendor/bin/free:samsung \
    vendor/samsung/a2corelte/proprietary/bin/getenforce:system/vendor/bin/getenforce:samsung \
    vendor/samsung/a2corelte/proprietary/bin/getprop:system/vendor/bin/getprop:samsung \
    vendor/samsung/a2corelte/proprietary/bin/grep:system/vendor/bin/grep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/groups:system/vendor/bin/groups:samsung \
    vendor/samsung/a2corelte/proprietary/bin/gunzip:system/vendor/bin/gunzip:samsung \
    vendor/samsung/a2corelte/proprietary/bin/gzip:system/vendor/bin/gzip:samsung \
    vendor/samsung/a2corelte/proprietary/bin/head:system/vendor/bin/head:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hostapd:system/vendor/bin/hostapd:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hostname:system/vendor/bin/hostname:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hwclock:system/vendor/bin/hwclock:samsung \
    vendor/samsung/a2corelte/proprietary/bin/id:system/vendor/bin/id:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ifconfig:system/vendor/bin/ifconfig:samsung \
    vendor/samsung/a2corelte/proprietary/bin/inotifyd:system/vendor/bin/inotifyd:samsung \
    vendor/samsung/a2corelte/proprietary/bin/insmod:system/vendor/bin/insmod:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ionice:system/vendor/bin/ionice:samsung \
    vendor/samsung/a2corelte/proprietary/bin/iorenice:system/vendor/bin/iorenice:samsung \
    vendor/samsung/a2corelte/proprietary/bin/kill:system/vendor/bin/kill:samsung \
    vendor/samsung/a2corelte/proprietary/bin/killall:system/vendor/bin/killall:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ln:system/vendor/bin/ln:samsung \
    vendor/samsung/a2corelte/proprietary/bin/load_policy:system/vendor/bin/load_policy:samsung \
    vendor/samsung/a2corelte/proprietary/bin/log:system/vendor/bin/log:samsung \
    vendor/samsung/a2corelte/proprietary/bin/logname:system/vendor/bin/logname:samsung \
    vendor/samsung/a2corelte/proprietary/bin/losetup:system/vendor/bin/losetup:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ls:system/vendor/bin/ls:samsung \
    vendor/samsung/a2corelte/proprietary/bin/lsmod:system/vendor/bin/lsmod:samsung \
    vendor/samsung/a2corelte/proprietary/bin/lsof:system/vendor/bin/lsof:samsung \
    vendor/samsung/a2corelte/proprietary/bin/lspci:system/vendor/bin/lspci:samsung \
    vendor/samsung/a2corelte/proprietary/bin/lsusb:system/vendor/bin/lsusb:samsung \
    vendor/samsung/a2corelte/proprietary/bin/md5sum:system/vendor/bin/md5sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/microcom:system/vendor/bin/microcom:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mkdir:system/vendor/bin/mkdir:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mkfifo:system/vendor/bin/mkfifo:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mknod:system/vendor/bin/mknod:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mkswap:system/vendor/bin/mkswap:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mktemp:system/vendor/bin/mktemp:samsung \
    vendor/samsung/a2corelte/proprietary/bin/modinfo:system/vendor/bin/modinfo:samsung \
    vendor/samsung/a2corelte/proprietary/bin/modprobe:system/vendor/bin/modprobe:samsung \
    vendor/samsung/a2corelte/proprietary/bin/more:system/vendor/bin/more:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mount:system/vendor/bin/mount:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mountpoint:system/vendor/bin/mountpoint:samsung \
    vendor/samsung/a2corelte/proprietary/bin/mv:system/vendor/bin/mv:samsung \
    vendor/samsung/a2corelte/proprietary/bin/netstat:system/vendor/bin/netstat:samsung \
    vendor/samsung/a2corelte/proprietary/bin/nice:system/vendor/bin/nice:samsung \
    vendor/samsung/a2corelte/proprietary/bin/nl:system/vendor/bin/nl:samsung \
    vendor/samsung/a2corelte/proprietary/bin/nohup:system/vendor/bin/nohup:samsung \
    vendor/samsung/a2corelte/proprietary/bin/od:system/vendor/bin/od:samsung \
    vendor/samsung/a2corelte/proprietary/bin/paste:system/vendor/bin/paste:samsung \
    vendor/samsung/a2corelte/proprietary/bin/patch:system/vendor/bin/patch:samsung \
    vendor/samsung/a2corelte/proprietary/bin/pgrep:system/vendor/bin/pgrep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/pidof:system/vendor/bin/pidof:samsung \
    vendor/samsung/a2corelte/proprietary/bin/pkill:system/vendor/bin/pkill:samsung \
    vendor/samsung/a2corelte/proprietary/bin/pmap:system/vendor/bin/pmap:samsung \
    vendor/samsung/a2corelte/proprietary/bin/printenv:system/vendor/bin/printenv:samsung \
    vendor/samsung/a2corelte/proprietary/bin/printf:system/vendor/bin/printf:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ps:system/vendor/bin/ps:samsung \
    vendor/samsung/a2corelte/proprietary/bin/pwd:system/vendor/bin/pwd:samsung \
    vendor/samsung/a2corelte/proprietary/bin/readlink:system/vendor/bin/readlink:samsung \
    vendor/samsung/a2corelte/proprietary/bin/realpath:system/vendor/bin/realpath:samsung \
    vendor/samsung/a2corelte/proprietary/bin/renice:system/vendor/bin/renice:samsung \
    vendor/samsung/a2corelte/proprietary/bin/restorecon:system/vendor/bin/restorecon:samsung \
    vendor/samsung/a2corelte/proprietary/bin/rm:system/vendor/bin/rm:samsung \
    vendor/samsung/a2corelte/proprietary/bin/rmdir:system/vendor/bin/rmdir:samsung \
    vendor/samsung/a2corelte/proprietary/bin/rmmod:system/vendor/bin/rmmod:samsung \
    vendor/samsung/a2corelte/proprietary/bin/runcon:system/vendor/bin/runcon:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sed:system/vendor/bin/sed:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sendevent:system/vendor/bin/sendevent:samsung \
    vendor/samsung/a2corelte/proprietary/bin/seq:system/vendor/bin/seq:samsung \
    vendor/samsung/a2corelte/proprietary/bin/setenforce:system/vendor/bin/setenforce:samsung \
    vendor/samsung/a2corelte/proprietary/bin/setprop:system/vendor/bin/setprop:samsung \
    vendor/samsung/a2corelte/proprietary/bin/setsid:system/vendor/bin/setsid:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sh:system/vendor/bin/sh:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sha1sum:system/vendor/bin/sha1sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sha224sum:system/vendor/bin/sha224sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sha256sum:system/vendor/bin/sha256sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sha384sum:system/vendor/bin/sha384sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sha512sum:system/vendor/bin/sha512sum:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sleep:system/vendor/bin/sleep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sort:system/vendor/bin/sort:samsung \
    vendor/samsung/a2corelte/proprietary/bin/split:system/vendor/bin/split:samsung \
    vendor/samsung/a2corelte/proprietary/bin/start:system/vendor/bin/start:samsung \
    vendor/samsung/a2corelte/proprietary/bin/stat:system/vendor/bin/stat:samsung \
    vendor/samsung/a2corelte/proprietary/bin/stop:system/vendor/bin/stop:samsung \
    vendor/samsung/a2corelte/proprietary/bin/strings:system/vendor/bin/strings:samsung \
    vendor/samsung/a2corelte/proprietary/bin/swapoff:system/vendor/bin/swapoff:samsung \
    vendor/samsung/a2corelte/proprietary/bin/swapon:system/vendor/bin/swapon:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sync:system/vendor/bin/sync:samsung \
    vendor/samsung/a2corelte/proprietary/bin/sysctl:system/vendor/bin/sysctl:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tac:system/vendor/bin/tac:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tail:system/vendor/bin/tail:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tar:system/vendor/bin/tar:samsung \
    vendor/samsung/a2corelte/proprietary/bin/taskset:system/vendor/bin/taskset:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tee:system/vendor/bin/tee:samsung \
    vendor/samsung/a2corelte/proprietary/bin/time:system/vendor/bin/time:samsung \
    vendor/samsung/a2corelte/proprietary/bin/timeout:system/vendor/bin/timeout:samsung \
    vendor/samsung/a2corelte/proprietary/bin/top:system/vendor/bin/top:samsung \
    vendor/samsung/a2corelte/proprietary/bin/touch:system/vendor/bin/touch:samsung \
    vendor/samsung/a2corelte/proprietary/bin/toybox_vendor:system/vendor/bin/toybox_vendor:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tr:system/vendor/bin/tr:samsung \
    vendor/samsung/a2corelte/proprietary/bin/true:system/vendor/bin/true:samsung \
    vendor/samsung/a2corelte/proprietary/bin/truncate:system/vendor/bin/truncate:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tty:system/vendor/bin/tty:samsung \
    vendor/samsung/a2corelte/proprietary/bin/tzdaemon:system/vendor/bin/tzdaemon:samsung \
    vendor/samsung/a2corelte/proprietary/bin/ulimit:system/vendor/bin/ulimit:samsung \
    vendor/samsung/a2corelte/proprietary/bin/umount:system/vendor/bin/umount:samsung \
    vendor/samsung/a2corelte/proprietary/bin/uname:system/vendor/bin/uname:samsung \
    vendor/samsung/a2corelte/proprietary/bin/uniq:system/vendor/bin/uniq:samsung \
    vendor/samsung/a2corelte/proprietary/bin/unix2dos:system/vendor/bin/unix2dos:samsung \
    vendor/samsung/a2corelte/proprietary/bin/uptime:system/vendor/bin/uptime:samsung \
    vendor/samsung/a2corelte/proprietary/bin/usleep:system/vendor/bin/usleep:samsung \
    vendor/samsung/a2corelte/proprietary/bin/uudecode:system/vendor/bin/uudecode:samsung \
    vendor/samsung/a2corelte/proprietary/bin/uuencode:system/vendor/bin/uuencode:samsung \
    vendor/samsung/a2corelte/proprietary/bin/vmstat:system/vendor/bin/vmstat:samsung \
    vendor/samsung/a2corelte/proprietary/bin/vndservice:system/vendor/bin/vndservice:samsung \
    vendor/samsung/a2corelte/proprietary/bin/vndservicemanager:system/vendor/bin/vndservicemanager:samsung \
    vendor/samsung/a2corelte/proprietary/bin/wc:system/vendor/bin/wc:samsung \
    vendor/samsung/a2corelte/proprietary/bin/which:system/vendor/bin/which:samsung \
    vendor/samsung/a2corelte/proprietary/bin/whoami:system/vendor/bin/whoami:samsung \
    vendor/samsung/a2corelte/proprietary/bin/xargs:system/vendor/bin/xargs:samsung \
    vendor/samsung/a2corelte/proprietary/bin/xxd:system/vendor/bin/xxd:samsung \
    vendor/samsung/a2corelte/proprietary/bin/yes:system/vendor/bin/yes:samsung \
    vendor/samsung/a2corelte/proprietary/bin/zcat:system/vendor/bin/zcat:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.audio@2.0-service:system/vendor/bin/hw/android.hardware.audio@2.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.bluetooth@1.0-service:system/vendor/bin/hw/android.hardware.bluetooth@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.camera.provider@2.4-service:system/vendor/bin/hw/android.hardware.camera.provider@2.4-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.configstore@1.0-service:system/vendor/bin/hw/android.hardware.configstore@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.drm@1.0-service:system/vendor/bin/hw/android.hardware.drm@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.drm@1.0-service.widevine:system/vendor/bin/hw/android.hardware.drm@1.0-service.widevine:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.gatekeeper@1.0-service:system/vendor/bin/hw/android.hardware.gatekeeper@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.graphics.allocator@2.0-service:system/vendor/bin/hw/android.hardware.graphics.allocator@2.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.graphics.composer@2.1-service:system/vendor/bin/hw/android.hardware.graphics.composer@2.1-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.health@1.0-service:system/vendor/bin/hw/android.hardware.health@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.keymaster@3.0-service:system/vendor/bin/hw/android.hardware.keymaster@3.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.light@2.0-service:system/vendor/bin/hw/android.hardware.light@2.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.media.omx@1.0-service:system/vendor/bin/hw/android.hardware.media.omx@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.memtrack@1.0-service:system/vendor/bin/hw/android.hardware.memtrack@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.power@1.0-service:system/vendor/bin/hw/android.hardware.power@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.sensors@1.0-service:system/vendor/bin/hw/android.hardware.sensors@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.thermal@1.0-service:system/vendor/bin/hw/android.hardware.thermal@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.vibrator@1.0-service:system/vendor/bin/hw/android.hardware.vibrator@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/android.hardware.wifi@1.0-service:system/vendor/bin/hw/android.hardware.wifi@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/gpsd:system/vendor/bin/hw/gpsd:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/macloader:system/vendor/bin/hw/macloader:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/mfgloader:system/vendor/bin/hw/mfgloader:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/rild:system/vendor/bin/hw/rild:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/vendor.samsung.hardware.gnss@1.0-service:system/vendor/bin/hw/vendor.samsung.hardware.gnss@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/vendor.samsung.hardware.miscpower@1.0-service:system/vendor/bin/hw/vendor.samsung.hardware.miscpower@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service:system/vendor/bin/hw/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service:samsung \
    vendor/samsung/a2corelte/proprietary/bin/hw/wpa_supplicant:system/vendor/bin/hw/wpa_supplicant:samsung \
    vendor/samsung/a2corelte/proprietary/etc/NOTICE.xml.gz:system/vendor/etc/NOTICE.xml.gz:samsung \
    vendor/samsung/a2corelte/proprietary/etc/SoundBoosterParam.txt:system/vendor/etc/SoundBoosterParam.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/a2dp_audio_policy_configuration.xml:system/vendor/etc/a2dp_audio_policy_configuration.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/audio_effects_common.conf:system/vendor/etc/audio_effects_common.conf:samsung \
    vendor/samsung/a2corelte/proprietary/etc/audio_policy_configuration.xml:system/vendor/etc/audio_policy_configuration.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/audio_policy_configuration_sec.xml:system/vendor/etc/audio_policy_configuration_sec.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/audio_policy_volumes.xml:system/vendor/etc/audio_policy_volumes.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/default_volume_tables.xml:system/vendor/etc/default_volume_tables.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/fs_config_dirs:system/vendor/etc/fs_config_dirs:samsung \
    vendor/samsung/a2corelte/proprietary/etc/fs_config_files:system/vendor/etc/fs_config_files:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs.xml:system/vendor/etc/media_codecs.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs_google_audio.xml:system/vendor/etc/media_codecs_google_audio.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs_google_telephony.xml:system/vendor/etc/media_codecs_google_telephony.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs_google_video.xml:system/vendor/etc/media_codecs_google_video.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs_google_video_le.xml:system/vendor/etc/media_codecs_google_video_le.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_codecs_performance.xml:system/vendor/etc/media_codecs_performance.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/media_profiles_V1_0.xml:system/vendor/etc/media_profiles_V1_0.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/mixer_gains.xml:system/vendor/etc/mixer_gains.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/mixer_paths.xml:system/vendor/etc/mixer_paths.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/mkshrc:system/vendor/etc/mkshrc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/plmn_delta.bin:system/vendor/etc/plmn_delta.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/plmn_delta_attaio.bin:system/vendor/etc/plmn_delta_attaio.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/plmn_delta_usacdma.bin:system/vendor/etc/plmn_delta_usacdma.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/plmn_delta_usagsm.bin:system/vendor/etc/plmn_delta_usagsm.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/plmn_se13.bin:system/vendor/etc/plmn_se13.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/public.libraries.txt:system/vendor/etc/public.libraries.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/r_submix_audio_policy_configuration.xml:system/vendor/etc/r_submix_audio_policy_configuration.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/usb_audio_policy_configuration.xml:system/vendor/etc/usb_audio_policy_configuration.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/ACG/permissions/android.hardware.telephony.cdma.xml:system/vendor/etc/carrier/ACG/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/BST/permissions/android.hardware.telephony.cdma.xml:system/vendor/etc/carrier/BST/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/CCT/permissions/android.hardware.telephony.cdma.xml:system/vendor/etc/carrier/CCT/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/LRA/permissions/android.hardware.telephony.cdma.xml:system/vendor/etc/carrier/LRA/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/SPR/permissions/android.hardware.telephony.cdma.xml:system/vendor/etc/carrier/SPR/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/TFN/permissions/android.hardware.telephony.cdma.xml:system/vendor/etc/carrier/TFN/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/USC/permissions/android.hardware.telephony.cdma.xml:system/vendor/etc/carrier/USC/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/VMU/permissions/android.hardware.telephony.cdma.xml:system/vendor/etc/carrier/VMU/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/VZW/permissions/android.hardware.telephony.cdma.xml:system/vendor/etc/carrier/VZW/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/carrier/XAS/permissions/android.hardware.telephony.cdma.xml:system/vendor/etc/carrier/XAS/permissions/android.hardware.telephony.cdma.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/gnss/ca.pem:system/vendor/etc/gnss/ca.pem:samsung \
    vendor/samsung/a2corelte/proprietary/etc/gnss/gps.cfg:system/vendor/etc/gnss/gps.cfg:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.audio@2.0-service.rc:system/vendor/etc/init/android.hardware.audio@2.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.bluetooth@1.0-service.rc:system/vendor/etc/init/android.hardware.bluetooth@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.camera.provider@2.4-service.rc:system/vendor/etc/init/android.hardware.camera.provider@2.4-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.configstore@1.0-service.rc:system/vendor/etc/init/android.hardware.configstore@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.drm@1.0-service.rc:system/vendor/etc/init/android.hardware.drm@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.drm@1.0-service.widevine.rc:system/vendor/etc/init/android.hardware.drm@1.0-service.widevine.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.gatekeeper@1.0-service.rc:system/vendor/etc/init/android.hardware.gatekeeper@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.graphics.allocator@2.0-service.rc:system/vendor/etc/init/android.hardware.graphics.allocator@2.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.graphics.composer@2.1-service.rc:system/vendor/etc/init/android.hardware.graphics.composer@2.1-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.health@1.0-service.rc:system/vendor/etc/init/android.hardware.health@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.keymaster@3.0-service.rc:system/vendor/etc/init/android.hardware.keymaster@3.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.light@2.0-service.rc:system/vendor/etc/init/android.hardware.light@2.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.media.omx@1.0-service.rc:system/vendor/etc/init/android.hardware.media.omx@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.memtrack@1.0-service.rc:system/vendor/etc/init/android.hardware.memtrack@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.power@1.0-service.rc:system/vendor/etc/init/android.hardware.power@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.sensors@1.0-service.rc:system/vendor/etc/init/android.hardware.sensors@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.thermal@1.0-service.rc:system/vendor/etc/init/android.hardware.thermal@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.vibrator@1.0-service.rc:system/vendor/etc/init/android.hardware.vibrator@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/android.hardware.wifi@1.0-service.rc:system/vendor/etc/init/android.hardware.wifi@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/hostapd.android.rc:system/vendor/etc/init/hostapd.android.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/init.vendor.rilchip.rc:system/vendor/etc/init/init.vendor.rilchip.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/init.vendor.rilcommon.rc:system/vendor/etc/init/init.vendor.rilcommon.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/rild.rc:system/vendor/etc/init/rild.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/vendor.samsung.hardware.gnss@1.0-service.rc:system/vendor/etc/init/vendor.samsung.hardware.gnss@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/vendor.samsung.hardware.miscpower@1.0-service.rc:system/vendor/etc/init/vendor.samsung.hardware.miscpower@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service.rc:system/vendor/etc/init/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/init/vndservicemanager.rc:system/vendor/etc/init/vndservicemanager.rc:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/AzControlParams_SPEAKER.txt:system/vendor/etc/nxp/AzControlParams_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/LVAZFS_Configuration.txt:system/vendor/etc/nxp/LVAZFS_Configuration.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/LVVEFS_Rx_Configuration.txt:system/vendor/etc/nxp/voiceexperience/LVVEFS_Rx_Configuration.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/LVVEFS_Tx_Configuration.txt:system/vendor/etc/nxp/voiceexperience/LVVEFS_Tx_Configuration.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_EARPIECE.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_SPEAKER.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_EARPIECE.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_SPEAKER.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET_NREC_ON.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/WifiCalling/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_EARPIECE.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_SPEAKER.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_EARPIECE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_SPEAKER.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/voiceexperience/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.camera.flash-autofocus.xml:system/vendor/etc/permissions/android.hardware.camera.flash-autofocus.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.camera.front.xml:system/vendor/etc/permissions/android.hardware.camera.front.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.camera.xml:system/vendor/etc/permissions/android.hardware.camera.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.location.gps.xml:system/vendor/etc/permissions/android.hardware.location.gps.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.opengles.aep.xml:system/vendor/etc/permissions/android.hardware.opengles.aep.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.sensor.accelerometer.xml:system/vendor/etc/permissions/android.hardware.sensor.accelerometer.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.sensor.proximity.xml:system/vendor/etc/permissions/android.hardware.sensor.proximity.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.telephony.gsm.xml:system/vendor/etc/permissions/android.hardware.telephony.gsm.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml:system/vendor/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.usb.accessory.xml:system/vendor/etc/permissions/android.hardware.usb.accessory.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.usb.host.xml:system/vendor/etc/permissions/android.hardware.usb.host.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.vulkan.level.xml:system/vendor/etc/permissions/android.hardware.vulkan.level.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.vulkan.version.xml:system/vendor/etc/permissions/android.hardware.vulkan.version.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.wifi.direct.xml:system/vendor/etc/permissions/android.hardware.wifi.direct.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/android.hardware.wifi.xml:system/vendor/etc/permissions/android.hardware.wifi.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/permissions/handheld_core_hardware.xml:system/vendor/etc/permissions/handheld_core_hardware.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/seccomp_policy/mediacodec.policy:system/vendor/etc/seccomp_policy/mediacodec.policy:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/nonplat_file_contexts:system/vendor/etc/selinux/nonplat_file_contexts:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/nonplat_hwservice_contexts:system/vendor/etc/selinux/nonplat_hwservice_contexts:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/nonplat_mac_permissions.xml:system/vendor/etc/selinux/nonplat_mac_permissions.xml:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/nonplat_property_contexts:system/vendor/etc/selinux/nonplat_property_contexts:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/nonplat_seapp_contexts:system/vendor/etc/selinux/nonplat_seapp_contexts:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/nonplat_sepolicy.cil:system/vendor/etc/selinux/nonplat_sepolicy.cil:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/nonplat_service_contexts:system/vendor/etc/selinux/nonplat_service_contexts:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/plat_sepolicy_vers.txt:system/vendor/etc/selinux/plat_sepolicy_vers.txt:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/precompiled_sepolicy:system/vendor/etc/selinux/precompiled_sepolicy:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/precompiled_sepolicy.plat_and_mapping.sha256:system/vendor/etc/selinux/precompiled_sepolicy.plat_and_mapping.sha256:samsung \
    vendor/samsung/a2corelte/proprietary/etc/selinux/vndservice_contexts:system/vendor/etc/selinux/vndservice_contexts:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_apsta.bin:system/vendor/etc/wifi/bcmdhd_apsta.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_apsta.bin_36:system/vendor/etc/wifi/bcmdhd_apsta.bin_36:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_clm.blob:system/vendor/etc/wifi/bcmdhd_clm.blob:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_mfg.bin:system/vendor/etc/wifi/bcmdhd_mfg.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_mfg.bin_36:system/vendor/etc/wifi/bcmdhd_mfg.bin_36:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_sta.bin:system/vendor/etc/wifi/bcmdhd_sta.bin:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/bcmdhd_sta.bin_36:system/vendor/etc/wifi/bcmdhd_sta.bin_36:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/cred.conf:system/vendor/etc/wifi/cred.conf:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/indoorchannel.info:system/vendor/etc/wifi/indoorchannel.info:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/nvram.txt_36:system/vendor/etc/wifi/nvram.txt_36:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/vendor/etc/wifi/p2p_supplicant_overlay.conf:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/wpa_supplicant.conf:system/vendor/etc/wifi/wpa_supplicant.conf:samsung \
    vendor/samsung/a2corelte/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/vendor/etc/wifi/wpa_supplicant_overlay.conf:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/bcm43436B0_V0086.0141.hcd:system/vendor/firmware/bcm43436B0_V0086.0141.hcd:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/bcm43436B0_V0096.0154.hcd:system/vendor/firmware/bcm43436B0_V0096.0154.hcd:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/setfile_5e9.bin:system/vendor/firmware/setfile_5e9.bin:samsung \
    vendor/samsung/a2corelte/proprietary/firmware/setfile_gc5035.bin:system/vendor/firmware/setfile_gc5035.bin:samsung \
    vendor/samsung/a2corelte/proprietary/lib/android.hidl.base@1.0.so:system/vendor/lib/android.hidl.base@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/camera.device@1.0-impl.so:system/vendor/lib/camera.device@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/camera.device@3.2-impl.so:system/vendor/lib/camera.device@3.2-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/camera.device@3.3-impl.so:system/vendor/lib/camera.device@3.3-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libExynosHWCService.so:system/vendor/lib/libExynosHWCService.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libExynosOMX_Core.so:system/vendor/lib/libExynosOMX_Core.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libExynosOMX_Resourcemanager.so:system/vendor/lib/libExynosOMX_Resourcemanager.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libLifevibes_lvverx.so:system/vendor/lib/libLifevibes_lvverx.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libLifevibes_lvvetx.so:system/vendor/lib/libLifevibes_lvvetx.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libMcClient.so:system/vendor/lib/libMcClient.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libOpenCL.so.1:system/vendor/lib/libOpenCL.so.1:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libOpenCL.so.1.1:system/vendor/lib/libOpenCL.so.1.1:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libSamsungPostProcessConvertor.so:system/vendor/lib/libSamsungPostProcessConvertor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/lib_SamsungRec_06006.so:system/vendor/lib/lib_SamsungRec_06006.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/lib_SoundAlive_SRC384_ver300.so:system/vendor/lib/lib_SoundAlive_SRC384_ver300.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/lib_soundaliveresampler.so:system/vendor/lib/lib_soundaliveresampler.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libalsautils.so:system/vendor/lib/libalsautils.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libandroid_ssrm.so:system/vendor/lib/libandroid_ssrm.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libarcsoft_beautyshot.so:system/vendor/lib/libarcsoft_beautyshot.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libarcsoft_beautyshot_preview.so:system/vendor/lib/libarcsoft_beautyshot_preview.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libaudio-ril.so:system/vendor/lib/libaudio-ril.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libaudioroute.so:system/vendor/lib/libaudioroute.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libavservices_minijail_vendor.so:system/vendor/lib/libavservices_minijail_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libcordon.so:system/vendor/lib/libcordon.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libcsc.so:system/vendor/lib/libcsc.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libeffects.so:system/vendor/lib/libeffects.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynoscamera.so:system/vendor/lib/libexynoscamera.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynoscamera3.so:system/vendor/lib/libexynoscamera3.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynosdisplay.so:system/vendor/lib/libexynosdisplay.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynosgscaler.so:system/vendor/lib/libexynosgscaler.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynosscaler.so:system/vendor/lib/libexynosscaler.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynosutils.so:system/vendor/lib/libexynosutils.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libexynosv4l2.so:system/vendor/lib/libexynosv4l2.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libfloatingfeature.so:system/vendor/lib/libfloatingfeature.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libhdmi.so:system/vendor/lib/libhdmi.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libhwc2on1adapter.so:system/vendor/lib/libhwc2on1adapter.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libhwcutils.so:system/vendor/lib/libhwcutils.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libhwjpeg.so:system/vendor/lib/libhwjpeg.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libhwminijail.so:system/vendor/lib/libhwminijail.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libion_exynos.so:system/vendor/lib/libion_exynos.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libkeymaster2_mdfpp.so:system/vendor/lib/libkeymaster2_mdfpp.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libkeymaster_helper.so:system/vendor/lib/libkeymaster_helper.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libkeystore-engine-wifi-hidl.so:system/vendor/lib/libkeystore-engine-wifi-hidl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libkeystore-wifi-hidl.so:system/vendor/lib/libkeystore-wifi-hidl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libmediacodecservice.so:system/vendor/lib/libmediacodecservice.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libminijail_vendor.so:system/vendor/lib/libminijail_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libmpbase.so:system/vendor/lib/libmpbase.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libmpbase_preview.so:system/vendor/lib/libmpbase_preview.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libmpp.so:system/vendor/lib/libmpp.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libnbaio_mono.so:system/vendor/lib/libnbaio_mono.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libpreprocessing_nxp.so:system/vendor/lib/libpreprocessing_nxp.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/librecordalive.so:system/vendor/lib/librecordalive.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libreference-ril.so:system/vendor/lib/libreference-ril.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libril.so:system/vendor/lib/libril.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/librilutils.so:system/vendor/lib/librilutils.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsamsungDiamondVoice.so:system/vendor/lib/libsamsungDiamondVoice.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsec-ril-dsds.so:system/vendor/lib/libsec-ril-dsds.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsec-ril.so:system/vendor/lib/libsec-ril.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsecaudioinfo.so:system/vendor/lib/libsecaudioinfo.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsecnativefeature.so:system/vendor/lib/libsecnativefeature.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libselinux_vendor.so:system/vendor/lib/libselinux_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsensorlistener.so:system/vendor/lib/libsensorlistener.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libsensorndkbridge.so:system/vendor/lib/libsensorndkbridge.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libstagefrighthw.so:system/vendor/lib/libstagefrighthw.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libstainkiller.so:system/vendor/lib/libstainkiller.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libteecl.so:system/vendor/lib/libteecl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libtinyalsa.so:system/vendor/lib/libtinyalsa.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libtinycompress.so:system/vendor/lib/libtinycompress.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libuniapi.so:system/vendor/lib/libuniapi.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libuniplugin.so:system/vendor/lib/libuniplugin.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libuuid.so:system/vendor/lib/libuuid.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libvideobeautycapture_interface.so:system/vendor/lib/libvideobeautycapture_interface.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libvideobeautypreview_interface.so:system/vendor/lib/libvideobeautypreview_interface.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libvirtualdisplay.so:system/vendor/lib/libvirtualdisplay.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libvndsecril-client.so:system/vendor/lib/libvndsecril-client.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libwebrtc_audio_preprocessing.so:system/vendor/lib/libwebrtc_audio_preprocessing.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libwifi-hal.so:system/vendor/lib/libwifi-hal.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libwpa_client.so:system/vendor/lib/libwpa_client.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libwrappergps.so:system/vendor/lib/libwrappergps.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/libwvhidl.so:system/vendor/lib/libwvhidl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.gnss@1.0.so:system/vendor/lib/vendor.samsung.hardware.gnss@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.miscpower@1.0.so:system/vendor/lib/vendor.samsung.hardware.miscpower@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.radio.channel@1.0_vendor.so:system/vendor/lib/vendor.samsung.hardware.radio.channel@1.0_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.radio.secoemhook@1.0_vendor.so:system/vendor/lib/vendor.samsung.hardware.radio.secoemhook@1.0_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.radio@1.1_vendor.so:system/vendor/lib/vendor.samsung.hardware.radio@1.1_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.wifi.sec_hostapd@1.0.so:system/vendor/lib/vendor.samsung.hardware.wifi.sec_hostapd@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.hardware.wifi.supplicant@1.0.so:system/vendor/lib/vendor.samsung.hardware.wifi.supplicant@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung.security.skeymaster@3.0_vendor.so:system/vendor/lib/vendor.samsung.security.skeymaster@3.0_vendor.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0.so:system/vendor/lib/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.audio.effect@2.0-impl.so:system/vendor/lib/hw/android.hardware.audio.effect@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.audio@2.0-impl.so:system/vendor/lib/hw/android.hardware.audio@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.bluetooth@1.0-impl.so:system/vendor/lib/hw/android.hardware.bluetooth@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.camera.provider@2.4-impl.so:system/vendor/lib/hw/android.hardware.camera.provider@2.4-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.drm@1.0-impl.so:system/vendor/lib/hw/android.hardware.drm@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.gatekeeper@1.0-impl.so:system/vendor/lib/hw/android.hardware.gatekeeper@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.gnss@1.0-impl.so:system/vendor/lib/hw/android.hardware.gnss@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.graphics.allocator@2.0-impl.so:system/vendor/lib/hw/android.hardware.graphics.allocator@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.graphics.composer@2.1-impl.so:system/vendor/lib/hw/android.hardware.graphics.composer@2.1-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.graphics.mapper@2.0-impl.so:system/vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.health@1.0-impl.so:system/vendor/lib/hw/android.hardware.health@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.keymaster@3.0-impl.so:system/vendor/lib/hw/android.hardware.keymaster@3.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.light@2.0-impl.so:system/vendor/lib/hw/android.hardware.light@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.memtrack@1.0-impl.so:system/vendor/lib/hw/android.hardware.memtrack@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.power@1.0-impl.so:system/vendor/lib/hw/android.hardware.power@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.sensors@1.0-impl.so:system/vendor/lib/hw/android.hardware.sensors@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.soundtrigger@2.0-impl.so:system/vendor/lib/hw/android.hardware.soundtrigger@2.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.thermal@1.0-impl.so:system/vendor/lib/hw/android.hardware.thermal@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/android.hardware.vibrator@1.0-impl.so:system/vendor/lib/hw/android.hardware.vibrator@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/audio.primary.default.so:system/vendor/lib/hw/audio.primary.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/audio.primary.universal7870_go.so:system/vendor/lib/hw/audio.primary.universal7870_go.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/audio.r_submix.default.so:system/vendor/lib/hw/audio.r_submix.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/audio.usb.default.so:system/vendor/lib/hw/audio.usb.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/camera.universal7870_go.so:system/vendor/lib/hw/camera.universal7870_go.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/gatekeeper.exynos7870.so:system/vendor/lib/hw/gatekeeper.exynos7870.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/gps.default.so:system/vendor/lib/hw/gps.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/gralloc.default.so:system/vendor/lib/hw/gralloc.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/gralloc.exynos5.so:system/vendor/lib/hw/gralloc.exynos5.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/hwcomposer.exynos5.so:system/vendor/lib/hw/hwcomposer.exynos5.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/keystore.mdfpp.so:system/vendor/lib/hw/keystore.mdfpp.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/lights.exynos5.so:system/vendor/lib/hw/lights.exynos5.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/local_time.default.so:system/vendor/lib/hw/local_time.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/memtrack.exynos5.so:system/vendor/lib/hw/memtrack.exynos5.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/power.default.so:system/vendor/lib/hw/power.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/power.universal7870_go.so:system/vendor/lib/hw/power.universal7870_go.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/sensors.universal7870_go.so:system/vendor/lib/hw/sensors.universal7870_go.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/vendor.samsung.hardware.gnss@1.0-impl.so:system/vendor/lib/hw/vendor.samsung.hardware.gnss@1.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/vendor.samsung.security.skeymaster@3.0-impl.so:system/vendor/lib/hw/vendor.samsung.security.skeymaster@3.0-impl.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/vibrator.default.so:system/vendor/lib/hw/vibrator.default.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/hw/vulkan.exynos5.so:system/vendor/lib/hw/vulkan.exynos5.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/mediacas/libclearkeycasplugin.so:system/vendor/lib/mediacas/libclearkeycasplugin.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.AVC.Decoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/vendor/lib/omx/libOMX.Exynos.AVC.Encoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.HEVC.Decoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/vendor/lib/omx/libOMX.Exynos.HEVC.Encoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/vendor/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.VP8.Decoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/vendor/lib/omx/libOMX.Exynos.VP8.Encoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.WMV.Decoder.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libLifevibes_lvverx.so:system/vendor/lib/soundfx/libLifevibes_lvverx.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libLifevibes_lvvetx.so:system/vendor/lib/soundfx/libLifevibes_lvvetx.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libbundlewrapper.so:system/vendor/lib/soundfx/libbundlewrapper.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libdownmix.so:system/vendor/lib/soundfx/libdownmix.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libeffectproxy.so:system/vendor/lib/soundfx/libeffectproxy.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libldnhncr.so:system/vendor/lib/soundfx/libldnhncr.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libreverbwrapper.so:system/vendor/lib/soundfx/libreverbwrapper.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/soundfx/libvisualizer.so:system/vendor/lib/soundfx/libvisualizer.so:samsung \
    vendor/samsung/a2corelte/proprietary/lib/vndk-sp/libion.so:system/vendor/lib/vndk-sp/libion.so:samsung \
    vendor/samsung/a2corelte/proprietary/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd:samsung \
    vendor/samsung/a2corelte/proprietary/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd:samsung \
    vendor/samsung/a2corelte/proprietary/overlay/framework-res__auto_generated_rro.apk:system/vendor/overlay/framework-res__auto_generated_rro.apk:samsung \
    vendor/samsung/a2corelte/proprietary/overlay/SysuiDarkTheme/SysuiDarkThemeOverlay.apk:system/vendor/overlay/SysuiDarkTheme/SysuiDarkThemeOverlay.apk:samsung \
    vendor/samsung/a2corelte/proprietary/tee/00000000-0000-0000-0000-474154454b45:system/vendor/tee/00000000-0000-0000-0000-474154454b45:samsung \
    vendor/samsung/a2corelte/proprietary/tee/00000000-0000-0000-0000-4b45594d5354:system/vendor/tee/00000000-0000-0000-0000-4b45594d5354:samsung \
    vendor/samsung/a2corelte/proprietary/tee/00000000-0000-0000-0000-505256544545:system/vendor/tee/00000000-0000-0000-0000-505256544545:samsung \
    vendor/samsung/a2corelte/proprietary/tee/startup.tzar:system/vendor/tee/startup.tzar:samsung \
    vendor/samsung/a2corelte/proprietary/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_:system/vendor/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_:samsung
